#by wenl
times:
  fade-in: 10
  stay: 70
  fade-out: 20
messages:
  # 可用变量
  # %player_name% 破坏者名称, %player_displayname% 破坏者显示名称, 
  # %destoryer_team_name% 破坏者队伍名称, %destoryer_team_displayname% 破坏者队伍显示名称, 
  # %destoried_team_name% 被破坏队伍名称, %destoried_team_displayname% 被破坏队伍显示名称
  self-title: "&c你家炸了"
  self-subtitle: "&c破坏者: &a%player_displayname% &f(%destoryer_team_displayname%&f)"
  others-title: "&c%destoried_team_displayname%&f的床已被破坏"
  others-subtitle: "&c破坏者: &a%player_displayname% &f(%destoryer_team_displayname%&f)"