name: BedwarsDestoryTitle
version: 1.0.0
description: Bedwars destory title.
author: wenl
main: cf.singnet.BedwarsDestoryTitle
depend: [BedwarsRel, ProtocolLib]
commands:
  BedwarsDestoryTitle:
    description: Main command of BedwarsDestoryTitle.
    aliases: bwdt
    permission: bwdt.admin
permissions:
  bedwarsdestorytitle.admin:
    description: Gives access to all BedwarsDestoryTitle commands.
    default: op